FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app

COPY package.json package-lock.json ./

COPY prisma ./prisma
COPY prisma.config.ts ./

RUN npm ci --ignore-scripts

COPY . .

CMD ["sh", "-c", "npx prisma generate && npm run worker"]