import { prisma } from "@/lib/prisma";
import { FileUploadStatus } from "@/app/generated/prisma";
import type { ParsedSort } from "@/features/shared/utils/sort";

export async function createPending(fileName: string, sourceFile: Buffer) {
  return prisma.fileUpload.create({
    data: {
      fileName,
      // Prisma's generated Bytes type wants Uint8Array<ArrayBuffer>
      // specifically; a Node Buffer is a Uint8Array<ArrayBufferLike>
      // (ArrayBufferLike also covers SharedArrayBuffer), so it doesn't
      // structurally match. `new Uint8Array(buffer)` copies into a plain
      // ArrayBuffer-backed view, which does.
      sourceFile: new Uint8Array(sourceFile),
      status: FileUploadStatus.PENDING,
    },
  });
}

export async function markProcessing(id: number) {
  return prisma.fileUpload.update({
    where: { id },
    data: {
      status: FileUploadStatus.PROCESSING,
      startedAt: new Date(),
    },
  });
}

export async function markSuccess(id: number, created: number) {
  return prisma.fileUpload.update({
    where: { id },
    data: {
      status: FileUploadStatus.SUCCESS,
      totalRows: created,
      createdCount: created,
      errorCount: 0,
      completedAt: new Date(),
    },
  });
}

export async function markRowErrors(
  id: number,
  params: { totalRows: number; errorCount: number; errorFile: Buffer },
) {
  return prisma.fileUpload.update({
    where: { id },
    data: {
      status: FileUploadStatus.FAILED,
      totalRows: params.totalRows,
      errorCount: params.errorCount,
      errorFile: new Uint8Array(params.errorFile),
      completedAt: new Date(),
    },
  });
}

export async function markStructuralFailure(id: number, errorMessage: string) {
  return prisma.fileUpload.update({
    where: { id },
    data: {
      status: FileUploadStatus.FAILED,
      errorMessage,
      completedAt: new Date(),
    },
  });
}

export async function getSourceFile(id: number) {
  return prisma.fileUpload.findUnique({
    where: { id },
    select: { sourceFile: true, fileName: true },
  });
}

export async function getErrorFile(id: number) {
  return prisma.fileUpload.findUnique({
    where: { id },
    select: { errorFile: true, fileName: true },
  });
}

export interface FindManyPaginatedParams {
  page: number;
  pageSize: number;
  sort?: ParsedSort<"createdAt">;
}

export async function findManyPaginated({
  page,
  pageSize,
  sort,
}: FindManyPaginatedParams) {
  const [items, total] = await Promise.all([
    prisma.fileUpload.findMany({
      orderBy: { createdAt: sort?.direction ?? "desc" },
      // sourceFile/errorFile are potentially large blobs — never select
      // them for the list view, only via the dedicated download routes.
      select: {
        id: true,
        fileName: true,
        status: true,
        totalRows: true,
        createdCount: true,
        errorCount: true,
        errorMessage: true,
        startedAt: true,
        completedAt: true,
        createdAt: true,
      },
      skip: (page - 1) * pageSize,
      take: pageSize,
    }),
    prisma.fileUpload.count(),
  ]);

  return { items, total };
}
